### ISSUE TITLE
Missing libs/remark-latest.min.js for 01Intro.html to show properly

### ISSUE THREAD

**Issue by ffancheng** [anastasiospanagiotelis/DimensionReduction#1]
Hi @anastasiospanagiotelis Currently the 01Intro.html is not showing properly both locally and on your [website](https://anastasiospanagiotelis.netlify.app/teaching/amsi2021/01intro/01intro). 

I noticed that you have not uploaded the `libs/remark-latest.min.js` file in the YAML to github, which might be the cause. Could you please double-check that?

**Comment by anastasiospanagiotelis** [comment]
I didn't want to track this in every folder.  You can create this by running ```xaringan::summon_remark()``` before knitting the rmd document.  I will make a note of this in the README
